### PR TITLE
tinirc: Configure address selection policy

### LINKED ISSUE #203: [BUG] Pot should run ip6addrctl on jail startup
**Describe the bug**
(Usually?) pot installations are based on ipv4, but without calling `ip6addrctl`, the default address selection policy uses IPv6 in case a domain has an AAAA record. This makes some tools chose the wrong protocol.

**To Reproduce**
Create a pot that is based on /tmp/tinirc, jexec into the running jail, then:

```
root@long_jail_name:/ # host www.google.com                                (1)
www.google.com has address 142.251.36.196
www.google.com has IPv6 address 2a00:1450:4016:809::2004
root@long_jail_name:/ # ping www.google.com                                (2)
ping: UDP connect: No route to host
root@long_jail_name:/ # ping -4 www.google.com                             (3)
PING www.google.com (142.250.184.196): 56 data bytes
64 bytes from 142.250.184.196: icmp_seq=0 ttl=59 time=5.146 ms
^C
root@long_jail_name:/ # service ip6addrctl start                           (4)
root@long_jail_name:/ # ping www.google.com                                (5)
PING www.google.com (142.250.184.196): 56 data bytes
64 bytes from 142.250.184.196: icmp_seq=0 ttl=59 time=5.164 ms
^C
```

1. The hostname lookup of www.google.com shows that it has both IN A and IN AAAA records.
2. Pinging www.google.com selects IPv6, which is not configured in the pot to have any routes to the outside world _and therefore fails_.
3. Pinging with an explicit protocol specification works as expected.
4. Running the ip6addrctl rc script configured the default of preferring IPv4.
5. Now ping works as expected (prefer IPv4).

**Expected behavior**
Expect 5. from above to work by default (prefer IPv4 in an IPv4 based pot).

**Additional context**
Fixing this should be fairly straightforward. The general question of course is how much of these things should be done by pot itself and which things should be done by the container's payload (some customized script).

Either way, in this case the fix is fairly simple - either call `service ip6addrctl start` like above,  or do what /etc/rc.d/ip6addrctl would do in _/tmp/tinirc_:

```
if sysctl -n kern.features.inet6 >/dev/null 2>&1; then
	${IP6ADDRCTL_CMD} flush >/dev/null 2>&1
	cat <<EOT | ${IP6ADDRCTL_CMD} install /dev/stdin
	::1/128          50      0
	::/0             40      1
	::ffff:0:0/96   100      4
	2002::/16        30      2
	2001::/32         5      5
	fc00::/7          3     13
	::/96             1      3
	fec0::/10         1     11
	3ffe::/16         1     12
EOT
fi
```

Maybe calling `service ip6addrctl start` (but not stopping in case that didn't work), might be some good real-world middle-ground solution, as it would allow less-stripped down images to override the default (by changing the `ip6addrctl_policy` in rc.conf), while those who create really stripped-down images (without /etc/rc.d) could still setup things in their own scriptwork as they want.

### PR DESCRIPTION
**Pull request by grembo**
In case of IPv4-only, give IPv4 addresses the highest precedence,
in other cases (IPv6/dual-stack), prefer IPv6 addresses.

This fixes dual-stack tools like ping.

Only implemented for tinirc, as pots running standard rc run
these commands by default.

While there, add "wait for epair" also for IPv6 and private vnet
interfaces.

Fixes #203

### CODE REVIEW

File: share/pot/start.sh [hunk 1]
```diff
@@ -152,7 +152,6 @@ _js_vnet()
 	_ip=$( _get_ip_var "$_pname" )
 	## if norcscript - write a ad-hoc one
 	if [ "$(_get_conf_var "$_pname" "pot.attr.no-rc-script")" = "YES" ]; then
-		touch "${POT_FS_ROOT}/jails/$_pname/m/tmp/tinirc"
 		cat >>"${POT_FS_ROOT}/jails/$_pname/m/tmp/tinirc" <<-EOT
```
Comment (grembo) [inline share/pot/start.sh:155]: removed these calls to touch, assuming they're not really needed (added address selection policy will always have created the file at this point). Please let me know if they should be put back in.

File: share/pot/start.sh [hunk 2]
```diff
@@ -427,6 +442,29 @@ _js_start()
...
+		        2002::/16	 30	 2
+		        2001::/32	  5	 5
+		        fc00::/7	  3	13
+		        ::/96		  1	 3
+		        fec0::/10	  1	11
+		        3ffe::/16	  1	12
+		EOF
+		fi
+		EOT
+	fi
```
Comment (grembo) [inline share/pot/start.sh:467]: This is the change for ip6addr policy (all the rest is adding missing epair checks). Let me know if this should also be divided. In general I think this is relatively clean solution.

File: share/pot/start.sh (hunk 1 above)
Comment (pizzamig) [reply share/pot/start.sh:155]: I guess `touch` is superfluous, `cat` will generate the file anyway

File: share/pot/start.sh (hunk 2 above)
Comment (pizzamig) [reply share/pot/start.sh:467]: the solution is clean, but there is one thing I'm unsure of: with `ipv4` stack or `ipv6` stack, does it make sense to have address selection policy? shouldn't it matters on `dual` only?

Comment (grembo) [reply share/pot/start.sh:467]: @pizzamig It is especially important on a non-dual _pot_ stack, specifically with ipv4, since `pot.stack=ipv4` is only about what pot configures in the jail, not about the OS/the vnet stack supporting IPv6.

# Example

    # pot create -p box -b 13.0 -t single -N public-bridge -S ipv4 && \
    pot set-attr -p box -A no-rc-script -V YES && \
    pot set-attr -p box -A persistent -V NO  && \
    pot set-cmd -p box -c '/sbin/ping -c3 www.google.com'
    # pot start box
    ===>  Starting the pot box
    add net default: gateway 10.192.0.1
    ping: UDP connect: No route to host 

    # pot set-cmd -p box \
    -c 'sh -c "service ip6addrctl start && /sbin/ping -c3 www.google.com"'
    # pot start box
    ===>  Starting the pot box
    add net default: gateway 10.192.0.1
    PING www.google.com (142.251.36.196): 56 data bytes
    64 bytes from 142.251.36.196: icmp_seq=0 ttl=118 time=15.412 ms
    64 bytes from 142.251.36.196: icmp_seq=1 ttl=118 time=13.560 ms
    64 bytes from 142.251.36.196: icmp_seq=2 ttl=118 time=14.952 ms
    # pot destroy -p box


# Explanation

What happens under the hood is:
- DNS lookup of www.google.com
- Resolver sees both A and AAAA records
- As the kernel supports IPv6, it checks the address selection policy
- Based on that, ping decides to ping www.google.com over IPv6
- Ping realizes that there is no route to www.google.com's IPv6 address (as we only have IPv6 on localhost, but no gateway for IPv6) and reports `UDP connect: No route to host `

Looking at interfaces inside the jail shows `lo0` holding `::1`:

    # pot create -p box -b 13.0 -t single -N public-bridge -S ipv4 && \
    pot set-attr -p box -A no-rc-script -V YES && \
    pot set-attr -p box -A persistent -V NO  && \
    pot set-cmd -p box -c '/sbin/ifconfig'
    # pot start box
    ===>  Starting the pot box
    add net default: gateway 10.192.0.1
    lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
    	options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
    	inet 127.0.0.1 netmask 0xff000000
    	inet6 ::1 prefixlen 128
    	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
    	groups: lo
    	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
    epair8b: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
    	options=8<VLAN_MTU>
    	ether ...
    	inet 10.192.0.4 netmask 0xffc00000 broadcast 10.255.255.255
    	groups: epair
    	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
    	status: active
    	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
    # pot destroy -p box

# Alternatives

Technically, there might be ways to somehow really disable IPv6 in the VNET stack of the pot, but I would recommend against that, as I don't think this is well tested and a lot of software expects to have an IPv6 stack available these days anyway.

Having both stacks enabled and configuring the IPv6 address selection policy is what happens on non-tinirc FreeBSD on every boot, that's why this was implemented here.

Comment (pizzamig) [reply share/pot/start.sh:467]: I totally got your point.
In my CI in the cloud, I set up ipv4 only and never encountered this issue. Happy to keep it as you proposed
